export const EMPTY_ACTION = 'EMPTY_ACTION';

export const ADD = {
  PLAYER: 'ADD_PLAYER',
};

export const CLEAR = {
  ADD_PLAYER: 'CLEAR_ADD_PLAYER',
  MESSAGE: 'CLEAR_MESSAGE',
  PLAYER: 'CLEAR_PLAYER',
};

export const UPDATE = {
  COUNTRIES: 'UPDATE_COUNTRIES',
  MESSAGE: 'UPDATE_MESSAGE',
  PLAYER: 'UPDATE_PLAYER',
  PLAYERS: 'UPDATE_PLAYERS',
};
